### ISSUE TITLE
null progress

### ISSUE THREAD

**Issue by genekogan** [abraham-ai/eden#11]
when fetching status update, in the beginning before any iterations have run, fetch returns `{ status: 'running', progress: null }`.

progress should not be null, it should either be 0, or perhaps more accurately, status should be reported as queued.

**Comment by Mayukhdeb** [comment]
Update:

if the user sets `progress = True` in a block, and then while running the block, if the progress has not been updated at least once, progress returns `'__none__'` by default. The progress starts holding a `float` value only after the user calls `config.progress.update(1/num__iters)` at least once

@genekogan  should I just set the initial default value to be `0.` instead of `'__none__'` ?
