### ISSUE TITLE
how to use storage

### ISSUE THREAD

**Issue by genekogan** [abraham-ai/eden#35]
requesting to add a server+client example of using the `results_storage` tied to the `ProgressTracker`. should show how the server can periodically update an image/text which is the output in progress, and how the client can retrieve it on fetch.

**Comment by Mayukhdeb** [comment]
I've cleaned up the the internal utils which I used to write results into redis. They can now be accessed and used from within the block as:

```python
intermediate_results = {
            "intermediate_creation": Image(intermediate_image),
            "width": width,
            "height": height
}
## write intermediate results
eden_block.write_results(output=intermediate_results, token=config.token)
```

There are no API changes to the client. Now instead of an empty `output` field on `fetch`, it gets filled up with your intermediate results. `status` remains untouched, and stays independent of whether we have intermediate outputs or not.
